services:
  # Exporter for Pi-hole metrics
  pihole-exporter:
    restart: always
    image: ekofr/pihole-exporter:latest
    network_mode: host
    environment:
      PIHOLE_HOSTNAME: "localhost"
      PIHOLE_PASSWORD: ${PIHOLE_ADMIN_PASSWORD}
      PIHOLE_PORT: "1080"
      PORT: "9617"
      DEBUG: "true"
    env_file:
      - .env
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--tries=1",
          "--spider",
          "http://localhost:9617/metrics",
        ]
      interval: 300s
      retries: 5
      timeout: 10s
    depends_on:
      - pihole
  pihole:
    restart: always
    container_name: pihole
    network_mode: host
    image: pihole/pihole:latest
    environment:
      # Set the appropriate timezone for your location (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones), e.g:
      TZ: "Europe/Copenhagen"
      # Set a password to access the web interface.
      WEBPASSWORD_FILE: pihole_admin_password
      # If using Docker's default `bridge` network setting the dns listening mode should be set to 'all'
      FTLCONF_dns_listeningMode: "all"
      # This will not allow iPhone users to use iCloud Private Relay, too bad :(
      FTLCONF_dns_specialDomains_iCloudPrivateRelay: "true"
      FTLCONF_webserver_port: "1080o,[::]:1080o,1443os,[::]:1443os"
    secrets:
      - pihole_admin_password
    # Volumes store your data between container upgrades
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - "/docker_data/pihole:/etc/pihole"
      # Logs
      - "/var/log/pihole:/var/log/pihole"
    cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      # Required if you are using Pi-hole as your DHCP server, else not needed
      - NET_ADMIN
      # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
      - SYS_TIME
      # Optional, if Pi-hole should get some more processing time
      - SYS_NICE
secrets:
  pihole_admin_password: # Needs notion write up
    file: /opt/secrets/PIHOLE_ADMIN_PASSWORD
